### ISSUE TITLE
Any plans to release the code?

### ISSUE THREAD

**Issue by C00reNUT** [avinashpaliwal/ReShader#1]

**Comment by avinashpaliwal** [comment]
I have been caught up in a few deadlines. We will release the code in the next 2-3 weeks.

**Comment by avinashpaliwal** [comment]
We merge our reshader code with the [3D Moments codebase](https://github.com/google-research/3d-moments). So if you can run their code, ours shouldn't present any problems. I'll also try to post the env file here soon.

**Comment by avinashpaliwal** [comment]
I have added the inference code. Training code and dataset will be released soon.
